In [2]:
import numpy as np

In [12]:
np.random.randint(100, 155, 2)

array([123, 115])

In [20]:
np.arange(5,10)

array([5])

In [22]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [27]:
ranarr = np.random.randint(5,90,12)

In [28]:
ranarr

array([80, 42, 14, 89, 62, 63, 11, 38, 63, 67, 28, 70])

In [31]:
ranarr.argmax()

3

In [32]:
ranarr.argmin()

6

In [35]:
ranarr.dtype

dtype('int32')

In [47]:
x = [1,2,3,4,2,3,5,5,55,9]

In [39]:
type(x)

list

In [40]:
arr = np.array(x)

In [41]:
arr

array([1, 2, 3])

In [42]:
x

[1, 2, 3]

In [55]:
arr[:2]

array([1, 2])

In [51]:
x[:6]

[1, 2, 3, 4, 2, 3]

In [69]:
arr = np.arange(0,21)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [75]:
arr_cp = arr.copy()

In [76]:
arr_cp[:]=70

In [77]:
arr_cp

array([70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70])

In [81]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [113]:
arr_2d[:,:1]

array([[1],
       [4],
       [7]])

In [119]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
arr_2d = np.arange(50).reshape(5,10)

In [124]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])